name: Setup Crosup
description: Download, install, and setup Crosup to your path.
author: Tsiry Sandratraina
branding:
  icon: play-circle
  color: purple
inputs:
  version:
    description: Crosup version to install
    required: false
    default: v0.4.2
  packages:
    description: |
      Whitespace separated, pkgs to supplement the environment. eg.

      ```yaml
      +: |
        deno
        zig
      ```

      By default tea reads your developer environment and adds those packages.
      Specifying additional packages here is a way to augment that.
    required: false
outputs:
  version:
    description: Crosup version installed
  cache-hit:
    description: Was the install cached?
runs:
  using: node16
  main: dist/action.js