name: Setup Crosup
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup-crosup:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup Crosup
        uses: ./
        with:
          packages: |
            node
            zig
      - name: Verify Crosup
        run: crosup --version
      - name: Verify Node
        run: node --version
      - name: Verify Zig
        run: zig version
